# Generated by Django 4.2.11 on 2024-04-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Pedidos',
        ),
    ]
