# Generated by Django 4.2.11 on 2024-04-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_rename_todo_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
