# Generated by Django 4.2.11 on 2024-04-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_pedidos_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='Obser',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
