# Generated by Django 4.2.11 on 2024-04-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_pedidos_obser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='Obser',
            new_name='obser',
        ),
    ]
