# Generated by Django 4.2.11 on 2024-04-24 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='deadlie',
            new_name='deadline',
        ),
    ]
